development:
  adapter: postgresql
  encoding: unicode
  database: recipe
  pool: 5
  host: localhost
  username: postgres
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_test
  pool: 5
  username: postgres
  password: 12345

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
